[tool.black]
line_length = 100

[tool.pytest.ini_options]
addopts = "-v -Wdefault"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.flakehell]
exclude = ["build"]
max_line_length = 100
# c.f. https://github.com/flakehell/flakehell/issues/10
extended_default_ignore=[ ]

[tool.flakehell.plugins]
mccabe = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]
